### ISSUE TITLE
Problems to cartographer 3D

### ISSUE THREAD

**Issue by ZhouYixuanRobtic** [ytgcljj/cartographerVLP16imu3D#1]
My apologize for bothering you @ytgcljj , I'm struggling with cartographer 3D mapping now. I notice that you've made a successful 3D map. Can you teach me in this?
# 
My problems are also published in cartographer_ros issues [here](https://github.com/googlecartographer/cartographer_ros/issues/904)
# 
I think I've modified all my configuration files right, while can't get right map. Appreciate much for your kindly help in advance. 
# 
By the way, can I get your email address? I can pay for your advice.
You can contact with me by my email (zhouyixuan29@gmail.com).
Also I noticed that you use simplified Chinese, so we may both come from mainland of china.(If not,please ignore this line). Anyway, sorry for disturbing you again.

**Comment by ytgcljj** [comment]
我正在安装一个新的CARTO，也遇到问题了，我修改完了再告诉你吧

**Comment by ytgcljj** [comment]
我看了你的图，我以前遇到过，你一定要把IMU和VELODYN的方向标对

**Comment by ZhouYixuanRobtic** [comment]
我的问题在于依据什么去标定IMU and velodyne 的旋转？是根据实际三维空间中的位置吗？我在URDF中构造的位置需要和实际三维空间一致对吗？
很抱歉现在才回复，我放了几天假。

**Comment by ytgcljj** [comment]
只能自己先标定水平的角，再找航向角

**Comment by ZhouYixuanRobtic** [comment]
好的，谢谢你。我已经能成功建图了。
